version: "3"
services:
  mongodb:
    container_name: mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #   - mongo_data:/data/db
    #   - ./mongo_backup:/backup
    networks:
      - mongo_network

  mongo_express:
    container_name: mongo_express
    image: mongo-express    
    restart: always    
    ports:
      - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL : mongodb://root:example@mongodb:27017/
        ME_CONFIG_BASICAUTH: false
    # depends_on:
    #   - mongodb
    networks:
      - mongo_network

  # data_copy:
  #   image: busybox
  #   container_name: data_copy
  #   volumes:
  #     - mongo_data:/data_copy
  #     - ./final_backup:/backup_destination
  #   entrypoint: /bin/sh -c "cp -r /data_copy/* /backup_destination"
  #   networks:
  #     - mongo_network
  #   depends_on:
  #     - mongodb

# volumes:
#   mongo_data:

networks:
  mongo_network:
    driver: bridge
